name: ml-testing

channels:
  - conda-forge

dependencies:
  - pip
  - pygraphviz
  - numpy
  - pandas
  - matplotlib
  - numba
  - pip:
    - ploomber
    - jupyterlab
    - papermill
    - bubbly
    - pandas-profiling
    - seaborn
    - shap
    - eli5
    - pdpbox
    - ipywidgets
    - pytest
    - yapf
    - invoke